### ISSUE TITLE
What is the vision?

### ISSUE THREAD

**Issue by schoeps** [brewsci/homebrew-science#10]
I have many questions on how this repository will evolve...
-is `brewsci/homebrew-science` an archive or supposed to be a new maintained home for scientific software?
-do you aim at splitting `brewsci/homebrew-science` into smaller repositories according to discipline as you have done with `homebrew-bio`? if yes, I could help setting up `homebrew-numerics`.
-some formula have been previously moved from `homebrew-science` to core but have been crippled down in features during the process, i.e. from my point of view as a computational scientist important options were removed. Are these formulas now welcome to be reimported? (e.g. Octave, SuiteSparse etc.)
-I suggested during previous discussions to define a maintainer for each formula to (hopefully) improve code quality. Is that option still considered?

Thanks for your initiative @sjackman!

**Comment by dpo** [comment]
I have the same questions. FWIW I resumed work on https://github.com/dpo/homebrew-openblas.

**Comment by sjackman** [comment]
> is brewsci/homebrew-science an archive or supposed to be a new maintained home for scientific software?

Brewsci/science is an archive.

> do you aim at splitting brewsci/homebrew-science into smaller repositories according to discipline as you have done with homebrew-bio? if yes, I could help setting up homebrew-numerics.

I plan on maintaining the brewsci/bio tap for bioinformatics software. I invite others to create taps for other disciplines. Yes, you're welcome to help set up brewsci/numerics. @dpo Are you interested in a numerics tap?

> some formula have been previously moved from homebrew-science to core but have been crippled down in features during the process, i.e. from my point of view as a computational scientist important options were removed. Are these formulas now welcome to be reimported? (e.g. Octave, SuiteSparse etc.)

Options are problematic for a few reasons. They're not tested by CI and may harbour latent bugs. The interaction of options with each other is not tested. The impact of options on other packages that depend on that package is not tested. Using an option requires rebuilding the package from source.

Each of these causes build failures, leads to a pour user experience, users reporting difficult-to-troubleshoot issues, and consuming limited developer time. I would avoid options if at all possible. When a feature is reasonably popular and doesn't negatively impact other users of the package, such as enabling an optional feature, then that feature should be enabled by default for all users. In that case, you could open a PR against Homebrew/core to enable that feature (without an option). When enabling an option makes that formula incompatible with its reverse dependencies, it should probably be in its own formula with a different name. You could, for example, create a package `octave-openblas` if you were so inclined.

> I suggested during previous discussions to define a maintainer for each formula to (hopefully) improve code quality. Is that option still considered?

Yes, I like this idea. I'm thinking of using the GitHub CODEOWNERS feature.
See https://github.com/blog/2392-introducing-code-owners
and https://help.github.com/articles/about-codeowners/

**Comment by schoeps** [comment]
Ok, so there is the need for a new numerics repository. I prefer to keep Linux and Mac compatible, therefore using openblas seems natural. I dislike the idea of calling everything `*-openblas` but I will do some experiments. In either case one could start small and slowly port formula that people request or donate.  The repo can be here or at https://github.com/dpo/homebrew-openblas.
 
@sjackman will brewsci get a a CI for Mac and Linux?
@dpo what do think?

**Comment by dpo** [comment]
My intention with hombrew-openblas was to gather the formulae for numerical software from homebrew-science. I also would like to maintain both Mac and Linux compatibility. Ideally, we need to build bottles but I haven't had time to investigate how to do that. I'm happy to rename the repository and/or move it if that's best.

I appreciate the uncertainty about options but in scientific software, I find that they're necessary or many scientists will simply elect to build software from scratch instead of using the Homebrew formula. There must be a way to set up CI so at least a few option combinations are tested. It could be part of a formula's official maintainer's duties to also test option combinations locally before pulling a PR.

**Comment by sjackman** [comment]
> I dislike the idea of calling everything *-openblas

Aeshtetically, me too, but I think it's the only safe way forward. It should be possible to install `Brewsci/numerics` formulae in parallel with `Homebrew/core` formulae, and that's only possible if the formulae have different names. I'd recommend strongly against putting any formulae in Brewsci that duplicate the name of a formula in `Homebrew/core`.

> will brewsci get a a CI for Mac and Linux?

Yes, CircleCI tests the formulae and builds bottles for both Linux and macOS.

**Comment by sjackman** [comment]
For compatibility with `Homebrew/core`, I'd suggest using OpenBLAS on Linux and Accelerate on macOS. What is the argument to use OpenBLAS on macOS?

Regarding options, ultimately you're the maintainer of your tap, and you can choose what you think best. I'm simply passing on my experience that options are evil. =)

**Comment by dpo** [comment]
Accelerate on OSX has been a problem for a long time. Its LAPACK library is incomplete and it requires vecLibFort for Fortran single precision programs to work properly. I've spoken to some of the Accelerate developers and those issues will be fixed in the future but currently, OpenBLAS is the only free and portable solution.

To be clear, I agree with you about options. I just think they're a necessary evil.

**Comment by schoeps** [comment]
@dpo @sjackman so, how to conclude? shall we start `numerics` here? can we agree on an openblas workflow? (by the way, Accelerate made also a few strange choices which cause problems with octave, see the [mailing list](http://octave.1599824.n4.nabble.com/Re-Apple-atan2f-td3037234.html))

I will be happy to take care of `octave`, `getdp` and `gmsh` and their dependencies if necessary (which is sadly a lot: petsc, slepc, sundials, ...). This is stuff that I need anyhow for my research.

BTW I just got octave-devel working on mac with openblas, java, gui and all: https://github.com/schoeps/homebrew-openblas

**Comment by sjackman** [comment]
@dpo Have you thought of moving your repo to the `brewsci` organization?

**Comment by ilovezfs** [comment]
>The proper way to handle Accelerate is to write a solid blas dependency for Homebrew but I just don't have the time.

FYI, there are no longer `default_formula` style requirements available in Homebrew (that functionality is deprecated now), so the `depends_on :blas` idea no longer makes sense. It should be `depends_on "openblas"` or `depends_on "fooblas"`.

**Comment by dpo** [comment]
@ilovezfs Thanks for the heads up! I suppose one can still cook up their own requirements?!

@sjackman It would make sense to move to brewsci, but we should have a clear plan about how to handle BLAS/LAPACK. When Accelerate is fixed, it will probably be the way to go.

**Comment by schoeps** [comment]
@dpo I will continue to prefer openblas until apple makes accelerate free software (which is probably never going to happen). I agree with ideals of reproducible computational research, see e.g. the nice paper from John W. Eaton (https://doi.org/10.1016/j.jprocont.2012.04.006) or the works from Lorena Barba's group.

**Comment by sjackman** [comment]
> I suppose one can still cook up their own requirements?!

Yes, but I believe `default_formula` is both deprecated and non-functional. (I haven't yet confirmed that.)

**Comment by MikeMcQuaid** [comment]
> Yes, but I believe default_formula is both deprecated and non-functional. (I haven't yet confirmed that.) I'd suggest using hard dependencies rather than requirements.

Yes, this is the case.

**Comment by goxberry** [comment]
As a previous enthusiastic user of `homebrew-science`, one of the reasons I liked the project was that almost every package I'd want to use was either in `homebrew-science` or could be added to it. The proposed balkanization of the old repo into subtopics is a bit too much to keep track of, and the shuttering of the main repo (along with losing the history) makes relying on `homebrew` more risky than I'd like.

I've decided to migrate to using [Spack](https://github.com/spack/spack) instead because its lead developer (@tgamblin) is interested in making itself more friendly to former `homebrew-science` users by making itself more Homebrew-like. It's written in Python, has institutional backing from major US Department of Energy software projects (xSDK, Exascale Computing Project) and DOE national labs like Lawrence Livermore National Lab (disclosure: I work at LLNL), and more configuration options for installing scientific software packages. I'm told Kitware will be working on CI infrastructure for testing as well. It still needs some work to make it more Mac-friendly, but I am working on smoothing out the rough edges because it seems less risky to work on a project with a more certain future. I'd welcome anyone else interested in contributing.

@sjackman, thank you for taking the lead on `homebrew-science` and `brewsci`! I enjoyed using 
and contributing to the software, and I hope that the "new `homebrew-science`", whatever that may be, is successful moving forward.

**Comment by sjackman** [comment]
I have the time and interest to maintain bioinformatics formulae, which are being moved to https://github.com/brewsci/homebrew-bio. I welcome anyone that wishes to maintain a tap for other areas of maths and science in the https://github.com/brewsci GitHub organization, and I'll be happy to help those interested tap maintainers get set up with CI running on CircleCI on both Linux and macOS for building bottles.

@goxberry You're welcome of course to use whichever package manager best suits your purposes. If you're interested in creating and maintaining a Brewsci tap yourself, I'd be happy to help you set that up.

**Comment by sjackman** [comment]
@dpo Any further thoughts on migrating your tap to Brewsci?

**Comment by dpo** [comment]
I'm all for it but I'm a bit short of time again for the next two weeks or so. I'm also undecided regarding the names of formulae to avoid conflicts with core. Isn't `brew tap-pin` a way around the name clash problem?

**Comment by sjackman** [comment]
Ah, I found the other issue for this topic. https://github.com/dpo/homebrew-openblas/issues/44

**Comment by tgamblin** [comment]
Hi all: @goxberry suggested that I put a brief shout-out to you all here.  I don't want to step on any toes, especially with all the awesome work that @sjackman has done on on @brewsci.  So, this comment may seem a bit gauche.  But, as @goxberry said, over at @spack, we would welcome any interested @brewsci folks.  We have a very welcoming, computational-science-focused community, and could always use new contributors.  Especially savvy ones like yourselves.

Points that might be relevant here:
* You can have the same package built as many ways as you want, with different `blas` implementations, and different options.  This might help with dpo/homebrew-openblas#44.  You would just need to port `ceres-solver` to spack (we don't have that one), and make it depend on `blas` (which is a virtual dependency for *any* `blas`).
* You can have as many options on packages as you want. So you could try `ceres` with different `openblas` builds (`spack install ceres ^openblas`, `spack install ceres ^openblas +ilp64`, etc.)
* We've got octave and some extensions.  That part of the stack could be improved.

Downsides: Our focus has so far been on Linux and HPC, so we do not have quite the user experience of `brew` yet, but we are growing.  If you end up trying Spack, I'd love to hear suggestions about what we could add to make it better for you.

Anyway -- thanks again for all the work you all do for scientific packaging.  If you are interested in closer collaboration with Spack, let me know.
